import { ac_a } from './entityHitEntity/AutoClicker/ac_a.js';
import { ac_b } from './entityHitBlock/AutoClicker/ac_b.js';
import { nuker_a } from './blockBreak/Nuker/nuker_a.js';
import { speed_a } from './tickEvents/Speed/speed_a.js';
import { speed_b } from './tickEvents/Speed/speed_b.js';
import { nofall_a } from './tickEvents/NoFall/nofall_a.js';
import { killaura_a } from './entityHitEntity/Killaura/killaura_a.js';
import { killaura_b } from './entityHitEntity/Killaura/killaura_b.js';
import { killaura_c } from './entityHitEntity/Killaura/killaura_c.js';
import { killaura_d } from './entityHitEntity/Killaura/killaura_d.js';
import { killaura_e } from './entityHitEntity/Killaura/killaura_e.js';
import { surround_a } from './blockBreak/Surround/surround_a.js';
import { surround_b } from './blockPlace/Surround/surround_b.js';
import { scaffold_a } from './blockPlace/Scaffold/scaffold_a.js';
import { aura_a } from './blockPlace/Aura/aura_a.js';
import { reach_a } from './entityHitEntity/Reach/reach_a.js';
import { spam_a } from './chatSend/Spam/spam_a.js';
import { spam_b } from './chatSend/Spam/spam_b.js';
import { swinging_head } from './tickEvents/swinging_head.js';
import { spammer_a } from './chatSend/Spammer/spammer_a.js';
import { spammer_b } from './chatSend/Spammer/spammer_b.js';
import { spammer_c } from './chatSend/Spammer/spammer_c.js';
import { spammer_d } from './chatSend/Spammer/spammer_d.js';
import { invaildsprint_a } from './tickEvents/InvaildSprint/invaildsprint_a.js';
import { invaildsprint_b } from './tickEvents/InvaildSprint/invaildsprint_b.js';
import { invaildsprint_c } from './tickEvents/InvaildSprint/invaildsprint_c.js';
import { crasher_a } from './tickEvents/Crasher/crasher_a.js';
import { crasher_b } from './entityHitEntity/Crasher/crasher_b.js';
import { crasher_c } from './entitySpawn/Crasher/crasher_c.js';
import { items } from './tickEvents/Items/items.js';
import { aimbot_a } from './tickEvents/AimBot/aimbot_a.js';
import { fly_a } from './tickEvents/Fly/fly_a.js';
import { fly_b } from './tickEvents/Fly/fly_b.js';
import { autototem_a } from './EntityTriggerEvents/AutoTotem/autoTotem_a.js';
import { autototem_b } from './EntityTriggerEvents/AutoTotem/autoTotem_b.js';
import { autototem_c } from './EntityTriggerEvents/AutoTotem/autoTotem_c.js';
import { autoshield_a } from './EntityTriggerEvents/AutoTotem/autoShield_a.js';
import { autoshield_b } from './EntityTriggerEvents/AutoTotem/autoShield_b.js';
import { autoshield_c } from './EntityTriggerEvents/AutoTotem/autoShield_c.js';
import { autotool_a } from './entityHitBlock/AutoTool/autotool_a.js';
import { insteabreak_a } from './blockBreak/InsteaBreak/insteabreak_a.js';
import { hurt_event } from './entityHurt/hurt_event.js';
import { knockback_a } from './tickEvents/KnockBack/knockback_a.js';

function launch() {
    knockback_a();
    insteabreak_a();
    autotool_a();
    autototem_a();
    autototem_b();
    autototem_c();
    autoshield_a();
    autoshield_b();
    autoshield_c();
    aimbot_a();
    items();
    crasher_a();
    crasher_b();
    crasher_c();
    invaildsprint_a();
    invaildsprint_b();
    invaildsprint_c();
    spammer_a();
    spammer_b();
    spammer_c();
    spammer_d();
    swinging_head();
    spam_b();
    spam_a();
    reach_a();
    aura_a();
    ac_a();
    ac_b();
    nuker_a();
    speed_a();
    speed_b();
    nofall_a();
    killaura_a();
    killaura_b();
    killaura_c();
    killaura_d();
    killaura_e();
    surround_a();
    surround_b();
    scaffold_a();
    fly_a();
    fly_b();
    hurt_event()
};

export { launch }