import "./helps/about";
import "./helps/help";
import "./moderations/op";
import "./moderations/deop";
import "./moderations/rank"
import "./settings/toggles";
import "./settings/toggle";
import "./settings/passwords";
import "./settings/flagmode";